services:
  backend:
    build: ./backend
    container_name: ordura-backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
    networks:
      - ordura-net

  frontend:
    build: ./frontend
    container_name: ordura-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    networks:
      - ordura-net

  nginx:
    image: nginx:latest
    container_name: ordura-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - ordura-net

networks:
  ordura-net:
    driver: bridge
